### ISSUE TITLE
Changelog: v0.0rc0

### ISSUE THREAD

**Issue by ncanceill** [ncanceill/pdf_hide#10]
# Version 0.0 rc0 changelog

This is a changelog for version 0.0 release candidate 0. It will be closed on the release day.

Please do not comment. If you want to contribute, please [drop a new issue](./new).
## Changelog
- [x] Fixed bugs about custom range and nbits — #6 #7 #8
- [x] Fixed bugs about custom range — #14
- [x] Fixed bugs in tests automation — #13
- [x] Fixed bugs with terminal emulation — mainly c75e87fd79ce811151c18dac3675d65cc43b6c74
- [x] Packaged portable code — #11
- [x] Added multi-encoding support for datafile — #12
- [x] Refactored code — mainly 38b62834ddecd9f4da256da4a0750568b6047d3a and af0df6170524d55b32d608981b5c88280f9f7bb3
